DestraTech/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from users.views import profile


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r"", include("administrator.urls")),
    path(r"freezers/", include("freezers.urls")),
    path(r"smartracks/", include("smartracks.urls")),
    
    path(r'profile/', profile, name='profile'),

    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', user_views.register, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GreeTech-Django/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from users.views import profile
from administrator import restAPIs


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"", include("administrator.urls")),
    
    url(r'profile/', profile, name='profile'),

    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', user_views.register, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freezers/urls.py
from django.urls import path
from . import views, restAPIs

urlpatterns = [
    path("freezerWarehouse/", views.freezerWarehouse, name="freezerWarehouse"),
    path("freezerDevice/<int:pk>/", views.freezerDevice, name="freezerDevice"),
    path("freezerData/<int:pk>/", restAPIs.freezerData, name="freezerData"),
]

smartracks/urls.py
from django.urls import path
from . import views, restAPIs

urlpatterns = [
    path("main/", views.smartracks, name="smartracks"),
    path("warehouse/<int:pk>/", views.warehouse, name="warehouse"),


    path("cloud/<int:pk>/", restAPIs.warehouseData, name="cloudWarehouse"),
]

smartracks/models.py
from pickle import TRUE
from django.db import models


class Warehouse(models.Model):
    warehouseId = models.CharField(max_length=200, null=True)
    serverState = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.warehouseId


class Compartment(models.Model):
    compartment = models.CharField(max_length=10, null=True)
    warehouse = models.ForeignKey(
        Warehouse, on_delete=models.CASCADE, null=True)
    boxstate = models.CharField(max_length=10, null=True)
    code = models.CharField(max_length=10, null=True)
    livestatedisplay = models.CharField(max_length=10, null=True)
    livestaterelay = models.CharField(max_length=10, null=True)
    livestatefeedback = models.CharField(max_length=10, null=True)
    smartenable = models.CharField(max_length=10, null=True)
    
    def __str__(self):
        return self.compartment

smartracks/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Compartment, Warehouse
from pymongo import MongoClient
from django.http import JsonResponse, QueryDict
import requests
import json


@login_required
def smartracks(request):
    allData = Warehouse.objects.all()
    context = {"allData": allData}
    return render(request, "smartracks/smartrack.html", context)


@login_required
def warehouse(request, pk):
    warehouseObj = Warehouse.objects.get(id=pk)
    if request.method == "POST" and request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest":
        form_data = QueryDict(request.POST["serializedForm"].encode("ASCII"))
        url = "https://api.airliftgrocer.com/compartment/status"

        payload = json.dumps(
            {"warehouseId": warehouseObj.warehouseId,
                "rack": form_data["compartment"], "status": form_data["status"], "side": form_data["side"]}
        )
        headers = {"auth": "Groc3R@Sm@rtR@ck",
                   "Content-Type": "application/json"}

        response = requests.request("PUT", url, headers=headers, data=payload)

        if response.status_code == 200:
            return JsonResponse({"message": "Updated Successfully"})
        else:
            return JsonResponse({"message": "Request Failed"})
    allCompartments = Compartment.objects.filter(warehouse_id=pk)
    context = {"allCompartments": allCompartments}
    return render(request, "smartracks/warehouse.html", context)

smartracks/templates/smartracks/smartrack.html
{% extends 'administrator/baseTemplate.html' %}
{% load static %}
{% block content %}

<div class="row">
    {% for each in allData %}
    <div class="col-lg-3 col-6">
      <div class="small-box bg-info">
        <div class="inner">
          <h3>{{each.warehouseId}}</h3>
          <p>WareHouse ID</p>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>  
        <a href="{% url 'warehouse' each.id %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

smartracks/templates/smartracks/warehouse.html
{% extends 'administrator/baseTemplate.html' %}
{% load static %}
{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header border-0">
                        <h3 class="card-title">WareHouse Real Time Data</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool btn-sm">
                                <i class="fas fa-download"></i>
                            </a>
                            <a href="#" class="btn btn-tool btn-sm">
                                <i class="fas fa-bars"></i>
                            </a>
                        </div>
                    </div>
                    <div class="card-body table-responsive p-0">
                        <div class="container">
                            <table class="table table-striped table-valign-middle" id="demoTable" style="padding: 5px">
                                <thead>
                                    <tr>
                                        <th>Compartment</th>
                                        <th>BoxState</th>
                                        <th>Code</th>
                                        <th>Display Board status</th>
                                        <th>Relay Board status</th>
                                        <th>Feedback Board status</th>
                                        <th>Smart Enable</th>
                                        <th>Manual Update</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for each in allCompartments %}
                                    <tr>
                                        <td>{{each.compartment}}</td>
                                        <td>{{each.boxstate}}</td>
                                        <td>{{each.code}}</td>
                                        <td>{{each.livestatedisplay}}</td>
                                        <td>{{each.livestaterelay}}</td>
                                        <td>{{each.livestatefeedback}}</td>
                                        <td>{{each.smartenable}}</td>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-info"
                                                onclick="tableSelect('{{each.compartment}}')">
                                                Manual Update
                                            </button>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-lg">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="modalForm">
                <div class="modal-body">
                    <div class="row">
                        <input type="text" value="" id="id_compartment" name="compartment" hidden>
                        <div class="col-md-6">
                            <div id="div_id_status" class="form-group">
                                <label for="id_status" class=" requiredField">
                                    Status<span class="asteriskField">*</span>
                                </label>
                                <div class=""> <select name="status" class="select form-control" id="id_status">
                                        <option value="available">Available</option>
                                        <option value="occupied">Occupied</option>
                                        <option value="unlocked">Unlocked</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_side" class="form-group">
                                <label for="id_side" class=" requiredField">
                                    Side<span class="asteriskField">*</span>
                                </label>
                                <div class=""> <select name="side" class="select form-control" id="id_side">
                                        <option value="picker">Picker</option>
                                        <option value="rider">Rider</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" onclick="submitForm()">Save changes</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{%block extraScripts %}
<script>
    $(document).ready(function () {
        $('#demoTable').DataTable({
            "pageLength": 50
        });
        setTimeout(function () {
            window.location.reload();
        }, 30000);
    });
    function tableSelect(compartment) {
        $("#id_compartment").val(compartment);
        $("#modalTitle").html("Update: " + compartment);

        $("#modal-lg").modal('show')
    }
    function submitForm() {
        const serializedForm = $("#modalForm").serialize();
        $.ajax({
            url: window.location.href,
            type: 'POST',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            data: {
                'serializedForm': serializedForm
            },
            success: function (data) {
                window.location.reload()
            },
            error: function (data) {
                alert("Request Failed")
            }
        });
    }
</script>
{% endblock %}